### ISSUE TITLE
&ZeroWidthSpace Encoding Issue

### ISSUE THREAD

**Issue by bzmillerboy** [sanity-io/template-nextjs-personal-website#119]
**Describe the bug**

`&ZeroWidthSpace`/`U+200B` is being injected into the data fetched from Sanity. It can be seen in the DOM using dev tools or if you do `JSON.stringify(data)`. These invisible characters are causing mismatches in variables from my data and therefore having site wide impact on styling. Example: A block with a size field/attribute may have a value of "large" but my styling function returns default because it doesn't find a match for "large" because it's actually `large&ZeroWidthSpace`.

**To Reproduce**

1. Clone a fresh repo (https://github.com/sanity-io/template-nextjs-personal-website)
2. Set up repo and new Sanity dataset
3. Add starter content at http://localhost:3000/studio
4. See `&ZeroWidthSpace` in Dom using Chrome Dev Tools.

**Screenshots**
<img width="1309" alt="Screenshot 2023-11-23 at 10 41 30 AM" src="https://github.com/sanity-io/template-nextjs-personal-website/assets/1130899/ec629804-a28a-4a04-83af-35769343f029">

**Which versions of Sanity are you using?**

@sanity/cli (global)        3.16.4 (latest: 3.20.1)
@sanity/color-input          3.1.0 (up to date)
@sanity/demo                 1.0.2 (up to date)
@sanity/image-url            1.0.2 (up to date)
@sanity/overlays             2.0.2 (up to date)
@sanity/preview-url-secret   1.0.2 (latest: 1.2.0)
@sanity/react-loader         1.1.0 (up to date)
@sanity/table                1.0.1 (up to date)
@sanity/vision              3.20.0 (latest: 3.20.1)
sanity                      3.20.0 (latest: 3.20.1)
next-sanity": "6.0.5"

**What operating system are you using?**
MacOS Version 14

**Which versions of Node.js / npm are you running?**
node: v18.17.0
npm: 9.6.7

**Additional context**
It's not clear to me, at what point in the tech stack this issue resides but it appears it's occurring when fetching the data from Sanity, so perhaps `loadQuery.ts`.

I don't believe this issue is within the data itself, I've queried the data directly with Vision plugin and tested several datasets. I am using [a VS Code plugin](https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins) to assure these characters are not coming from the codebase.

This only occurs in local development and is not an issue when deployed to Vercel hosting. It is an issue when running `npm run build & npm run start`.

Update:
It appears that `&ZeroWidthSpace` is not the only zero width character being injected. After sanitizing values, I found other characters as well. `U+FEFF` `U+200D` `U+200C`

**Comment by bzmillerboy** [comment]
My temporary work around includes a function in `loadQuery.ts` that sanitizes the JSON and removes these unicode characters. However, this solution does not work for `useQuery.ts` without disabling the visual editing outlines. Perhaps this is an indication of the issue source.

```
function sanitizeData(data: any): any {
  let sanitizedData: string
  if (typeof data === 'string') {
    sanitizedData = data.replace(/[\p{C}]/gu, '')
  } else {
    sanitizedData = JSON.stringify(data).replace(/[\p{C}]/gu, '')
  }
  try {
    return JSON.parse(sanitizedData)
  } catch (error) {
    console.error('Error parsing sanitized data back into JSON:', error)
    return null
  }
}
```

```
export function loadPage(slug: string) {
  return loadQuery<PagePayload | null>(
    pagesBySlugQuery,
    { slug },
    { next: { tags: [`page:${slug}`] } },
  ).then((result) => ({ ...result, data: sanitizeData(result.data) }))
}
```

**Comment by geball** [comment]
@bzmillerboy This appears to be related to Content Source Maps. There are some details on troubleshooting and how to fix the issue documented [here](https://www.sanity.io/docs/loaders-and-overlays#f78abaafcf50); I'll bring this up with the Docs team so we can figure out how we could better surface that information when faced with your original issue.
