### ISSUE TITLE
Live Preview does not work

### ISSUE THREAD

**Issue by vohoanglong0107** [sanity-io/template-nextjs-personal-website#140]
**Describe the bug**

Live Preview in the presentation tool does not work.

**To Reproduce**

1. Deploy Repo as per README
2. Create a new branch called `dev`, add a trivial commit to README.md, then push the commit to trigger the preview deployment
3. Configure Sanity project to add CORS for preview deployment url
4. Navigate to Studio and open presentation view
5. Click fields and edit fields content

**Expected behavior**

The content should be updated in the presentation view as the content is being edited

**Screenshots**

https://github.com/sanity-io/template-nextjs-personal-website/assets/78085736/106680cf-0a13-42b6-82d4-f1c88eb221da

**Which versions of Sanity are you using?**

3.21.3

**What operating system are you using?**

Mac OS

**Which versions of Node.js / npm are you running?**

10.2.0
v21.1.0

**Additional context**

Freshly cloned repo
https://github.com/vohoanglong0107/nextjs-personal-website

**Security issue?**

**Comment by donalffons** [comment]
I'm experiencing the same issue. Cross-referencing https://github.com/sanity-io/visual-editing/issues/567.

**Comment by stipsan** [comment]
Fixed in `@sanity/react-loader` `v1.6.4`

**Comment by vohoanglong0107** [comment]
Can confirm it's working now. Thank @stipsan 🎉
