### ISSUE TITLE
Add @sanity/client to package.json to resolve TypeScript module resolution error

### ISSUE THREAD

**Issue by JohnGemstone** [sanity-io/template-nextjs-personal-website#148]
Typescript is having trouble picking up`@sanity/client/stega`. While `@sanity/client` is included as a dependency through `@sanity/react-loader`, it's not explicitly listed in package.json. To fix this add `@sanity/client`. Cheers!

**To Reproduce**

1. Go to `sanity/lib/client.ts`
2. Observe ts error: `Cannot find module '@sanity/client/stega' or its corresponding type declarations.ts(2307)`

**Expected behavior**

No error and type definitions for `createClient`

**Screenshots**
![image](https://github.com/sanity-io/template-nextjs-personal-website/assets/17420741/a936a628-80df-4d30-a05b-c7d0edeaac61)

**Comment by stipsan** [comment]
PR welcome 👍
