### ISSUE TITLE
Title is missing

### ISSUE THREAD

**Issue by markusjs** [sanity-io/template-nextjs-personal-website#272]
**Describe the bug**
The title of the site that is set in Sanity does not appear on the website. Tested with the Vercel site and a clean cloned site from this repo.

**Expected behavior**
That the title is coming from Sanity

**Screenshots**
<img width="1728" alt="image" src="https://github.com/sanity-io/template-nextjs-personal-website/assets/19786812/75c621f6-1525-40bd-876c-9037751a7584">

**Which versions of Sanity are you using?**
Latest

**Comment by stipsan** [comment]
Where do you set the title, exactly?

**Comment by markusjs** [comment]
Under "Home" in Sanity 
<img width="1385" alt="image" src="https://github.com/sanity-io/template-nextjs-personal-website/assets/19786812/f3465c94-0cc9-43e4-9999-9ee685243727">

**Comment by stipsan** [comment]
Ah k, you need to add a menu item for it to show up at the top:
![image](https://github.com/sanity-io/template-nextjs-personal-website/assets/81981/003cc5ac-8216-4b4e-88a1-18a3fb030277)
